#!/usr/bin/env ruby
# This command can be used to start muninator as standalone. You must set
# standalone: true in your environment


APP_PATH = File.expand_path('../../config/application',  __FILE__)
require File.expand_path('../../config/boot',  __FILE__)
require File.expand_path('../../config/environment',  __FILE__)

Muninator.boot_standalone
